### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by eleboss** [AHupuJR/REFID#1]
Hi Lei, 
Greeting,
I just read the paper, nice work for sure. But the details of the dataset seems lacking, which sensor did you use to capture the scene? I think it is a DAVIS? But current DAVISs are mostly in low res, so how did you get the high-res one? And how the GT is generated?
Best
Shijie

**Comment by AHupuJR** [comment]
Hi Shijie,

Yes the sensor we use is not publicly available yet, it is a prototype from Alpsentek and it is a DAVIS. As the price for high spatial resolution, the time resolution for events is lower than normal DAVIS (about 2ms instead of us order). We will release the dataset soon. The blurry image are synthesized from sharp images, as depicted in the paper.

Best regards,
Lei
